
spring:
  application:
    name: User-Service
  profiles:
    active:
      development

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/User
    username: postgres
    password: shruti121

server:
  port: 9092

