#spring:
#
server:
  port: 9081

spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: User-Service
  profiles:
    active: development

  datasource:
    url: jdbc:postgresql://localhost:5432/User
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: shruti121

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration